export default {
    name:'experiences',
    title:'Experiences',
    type: 'document',
    fields:[
        {
            name:'index',
           title:'Index',
           type:'string'
        },
            {
                name:'year',
               title:'Date',
               type:'string'
            },
           {
               name:'position',
               title:'Position',
               type:'string'
            },
            {
                name:'location',
                title:'Location',
                type:'string'
            },
            {
                name:'company',
                title:'Company',
                type:'string'
            },
            {
                name:'desc',
                title:'Desc',
                type:'string'
            },
            {
                name:'tag',
                title:'tag',
                type:'string'
            }
    ]
}